# https://github.com/hyprwm/hypridle/issues/200
# Temporarily downgraded sdbus-cpp to 2.2.1-1, upgrade system when hypridle is rebuilt

general {
    lock_cmd = (pidof hyprlock || hyprlock) & keepassxc --lock & ssh-add -D
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
