# Interacting with keepassxc:
# https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC
general {
    lock_cmd = dbus-send --type=method_call --dest=org.keepassxc.KeePassXC.MainWindow /keepassxc \
        org.keepassxc.KeePassXC.MainWindow.lockAllDatabases; \
        ssh-add -D; playerctl -a pause; (pidof hyprlock || hyprlock)
    unlock_cmd = killall hyprlock
    on_unlock_cmd = loginctl unlock-session
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'
}

listener {
    timeout = 600
    on-timeout = playerctl status | grep -q "Playing" || loginctl lock-session
}

listener {
    timeout = 1800
    on-timeout = playerctl status | grep -q "Playing" \ 
        || sudo docker ps --format "{{.Image}}" | grep -q "itzg/minecraft-server" \
        || systemctl suspend
}

listener {
    timeout = 10800
    on-timeout = sudo docker ps --format "{{.Image}}" | grep -q "itzg/minecraft-server" || systemctl suspend
}
